apiVersion: v1
kind: Service
metadata:
  name: {{ include "minikube-helm.fullname" . }}-api-svc
  labels:
    {{- include "minikube-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  selector:
    {{- include "minikube-helm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  type: {{ .Values.api.service.type }}
  ports:
    - port: {{ .Values.api.service.port }}
      targetPort: 8000
