apiVersion: v1
kind: Service
metadata:
  name: {{ include "minikube-helm.fullname" . }}-db-svc
  labels:
    {{- include "minikube-helm.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  selector:
    {{- include "minikube-helm.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
  type: {{ .Values.db.service.type }}
  ports:
    - name: postgres
      port: {{ .Values.db.service.port }}
      targetPort: 5432
      protocol: TCP
