db:
  image:
    repository: postgres
    tag: 12.1-alpine
    pullPolicy: IfNotPresent
  storageCapacity: 5G
  storageHostFolder: /data
  initialDelaySeconds: 10
  failureThreshold: 1
  periodSeconds: 5
  service:
    type: ClusterIP
    port: 5432
  config:
    # none | configmap | secret
    type: none
    name: db-config
    dbName: custom
    dbUser: custom
    dbPassword: custom
    nameKey: db_name
    userKey: db_user
    passwordKey: db_password
  resources: {}

api:
  image:
    repository: django-todo
    tag: latest
    pullPolicy: Never
  replicas: 3
  initialDelaySeconds: 5
  failureThreshold: 1
  periodSeconds: 5
  service:
    type: LoadBalancer
    port: 8080
  resources: {}
