FROM python:3.7.6-alpine

WORKDIR /app

RUN \
  apk update && \
  apk upgrade && \
  apk add --no-cache bash libpq && \
  apk add --no-cache --virtual build-dependencies build-base gcc git postgresql-dev && \
  git clone https://github.com/shacker/gtd.git /app && \
  pip install pipenv && \
  pipenv install --system --deploy --dev && \
  apk del build-dependencies

COPY local.py /app/project
COPY wait-for-it.sh /app/

# TODO: Add non root user

#CMD ["python", "manage.py", "migrate"]
#CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
