kind: PersistentVolume
apiVersion: v1
metadata:
  name: django-todo
  namespace: django-todo
spec:
  storageClassName: manual
  capacity:
    storage: 5G
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/django-todo
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres
  namespace: django-todo
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5G
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: django-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:12-alpine
          ports:
            - name: postgres
              containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: db_name
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: db_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: db_password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgredb
          readinessProbe:
            tcpSocket:
              port: postgres
            initialDelaySeconds: 10
            failureThreshold: 1
            periodSeconds: 5
      volumes:
        - name: postgredb
          persistentVolumeClaim:
            claimName: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: django-todo
spec:
  selector:
    app: postgres
  type: ClusterIP
  ports:
    - port: 5432
