apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: django-todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      initContainers:
        - name: migrator
          image: django-todo:latest
          imagePullPolicy: Never # minikube only
          env:
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: db_name
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: db_password
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
          command: ["python"]
          args: ["manage.py", "migrate"]
      containers:
        - name: app
          image: django-todo:latest
          imagePullPolicy: Never # minikube only
          env:
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: db_name
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: db_password
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
          command: ["python"]
          args: ["manage.py", "runserver", "0.0.0.0:8000"]
          ports:
            - name: http
              containerPort: 8000
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 5
            failureThreshold: 1
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: django-todo
spec:
  selector:
    app: web
  type: NodePort
  ports:
    - name: http
      port: 8000
      nodePort: 32222
